---
abstract: 'A tool for collaborative authoring of polyscopic documents'
author:
  - 'Salve J. Nilsen <sjn@kaizendo.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.95'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Kaizendo
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Action::RenderView: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Runtime: 5.8002
  Config::General: 0
  Moose: 0
  namespace::autoclean: 0
  perl: 5.8.5
version: 0.01
