# refer to http://www.yaml.org/spec/1.1/ for clarification on YAML collections
kaizendo:
  path: /home/sjn/src/Kaizendo/root/static/css/blueprint
  semantic_classes:
    "#footer": ".span-24 last"
    "#left_col, #section_nav, #aspect_nav, #site_logo, #updated": ".span-4"
    "#content": ".span-14"
    "#right_col, #comments, #help, #login": ".span-6 last"
